keys:
  - &admin_srid age1zdwstn787x2a7hllksjk0zpdx3wdvy3fju8hk33a583jtv3d8q9qsvzfan
  - &server_nammayatri age1t46w429zmn9zjm76434g449eqw5ya4yj9np6m5qqqflhnu2sdvxqnn7kud
  - &admin_aman age1qwdtmg2kaazf9765xvku7d33p8t2axmkr5y9mcdw4kmjk4zxnyyqkeg8ry
creation_rules:
  - path_regex: secrets.json$
    key_groups:
      - age:
        - *admin_srid
        - &admin_aman
        - *server_nammayatri
